export { default as Header } from './Header'
export { default as HeroSection } from './HeroSection'
export { default as ProductCategories } from './ProductCategories'
export { default as ChatWidget } from './ChatWidget'
export { default as Footer } from './Footer'
export { default as CustomDesign } from './CustomDesign'
export { default as About } from './About'
export { default as Products } from './Products'
